import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/section/Header";
import Footer from "../components/section/Footer";
import Providers from "../components/section/Providers";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/* Aquí solo renderizamos children (el contenido de la página) */}
          {children}

          {/* El Toaster sí debe ir aquí para que funcione en todas partes */}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
